# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcy.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(15, 15, 15);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(610, 170, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.plus.setFont(font)
        self.plus.setStyleSheet("QPushButton{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 37, 0);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 123, 0);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushBotton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"};")
        self.plus.setObjectName("plus")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(610, 260, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.minus.setFont(font)
        self.minus.setStyleSheet("QPushButton{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 37, 0);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 123, 0);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushBotton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"};")
        self.minus.setObjectName("minus")
        self.multiply = QtWidgets.QPushButton(self.centralwidget)
        self.multiply.setGeometry(QtCore.QRect(610, 350, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.multiply.setFont(font)
        self.multiply.setStyleSheet("QPushButton{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 37, 0);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 123, 0);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushBotton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"};")
        self.multiply.setObjectName("multiply")
        self.divide = QtWidgets.QPushButton(self.centralwidget)
        self.divide.setGeometry(QtCore.QRect(610, 450, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.divide.setFont(font)
        self.divide.setStyleSheet("QPushButton{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 37, 0);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 123, 0);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushBotton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"};")
        self.divide.setObjectName("divide")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(16, 10, 771, 111))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(48)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(34, 34, 34);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 48pt \"MS Shell Dlg 2\";")
        self.label.setText("")
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 140, 581, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(68, 68, 68);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:rgb(121, 121, 121);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushBotton:hover{\n"
"    color:\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"};")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(68, 68, 68);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:rgb(121, 121, 121);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushBotton:hover{\n"
"    color:\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"};")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(68, 68, 68);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:rgb(121, 121, 121);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushBotton:hover{\n"
"    color:\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"};")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(68, 68, 68);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:rgb(121, 121, 121);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushBotton:hover{\n"
"    color:\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"};")
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 3, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(68, 68, 68);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:rgb(121, 121, 121);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushBotton:hover{\n"
"    color:\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"};")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(68, 68, 68);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:rgb(121, 121, 121);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushBotton:hover{\n"
"    color:\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"};")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(68, 68, 68);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:rgb(121, 121, 121);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushBotton:hover{\n"
"    color:\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"};")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(68, 68, 68);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:rgb(121, 121, 121);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushBotton:hover{\n"
"    color:\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"};")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(68, 68, 68);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:rgb(121, 121, 121);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushBotton:hover{\n"
"    color:\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"};")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(68, 68, 68);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color:rgb(121, 121, 121);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushBotton:hover{\n"
"    color:\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"};")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.equals = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.equals.setFont(font)
        self.equals.setStyleSheet("QPushButton{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 186, 0);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 229, 0);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushBotton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"};")
        self.equals.setObjectName("equals")
        self.gridLayout.addWidget(self.equals, 3, 2, 1, 1)
        self.clear = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.clear.setFont(font)
        self.clear.setStyleSheet("QPushButton{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 186, 0);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 229, 0);\n"
"\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushBotton:hover{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(7, 7, 7);\n"
"\n"
"border-radius:20px;\n"
"};")
        self.clear.setObjectName("clear")
        self.gridLayout.addWidget(self.clear, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 540, 151, 20))
        self.label_2.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton_0.clicked.connect(self.method_0)
        self.pushButton_1.clicked.connect(self.method_1)
        self.pushButton_2.clicked.connect(self.method_2)
        self.pushButton_3.clicked.connect(self.method_3)
        self.pushButton_4.clicked.connect(self.method_4)
        self.pushButton_5.clicked.connect(self.method_5)
        self.pushButton_6.clicked.connect(self.method_6)
        self.pushButton_7.clicked.connect(self.method_7)
        self.pushButton_8.clicked.connect(self.method_8)
        self.pushButton_9.clicked.connect(self.method_9)
        self.plus.clicked.connect(self.method_plus)
        self.minus.clicked.connect(self.method_minus)
        self.multiply.clicked.connect(self.method_multiply)
        self.divide.clicked.connect(self.method_divide)
        self.equals.clicked.connect(self.method_equals)
        self.clear.clicked.connect(self.method_clear)

    def method_0(self):
        text = self.label.text()
        self.label.setText(text + "0")

    def method_1(self):
        text = self.label.text()
        self.label.setText(text + "1")

    def method_2(self):
        text = self.label.text()
        self.label.setText(text + "2")

    def method_3(self):
        text = self.label.text()
        self.label.setText(text + "3")

    def method_4(self):
        text = self.label.text()
        self.label.setText(text + "4")

    def method_5(self):
        text = self.label.text()
        self.label.setText(text + "5")

    def method_6(self):
        text = self.label.text()
        self.label.setText(text + "6")

    def method_7(self):
        text = self.label.text()
        self.label.setText(text + "7")

    def method_8(self):
        text = self.label.text()
        self.label.setText(text + "8")

    def method_9(self):
        text = self.label.text()
        self.label.setText(text + "9")

    def method_plus(self):
        text=self.label.text()
        self.label.setText(text+"+")

    def method_minus(self):
        text = self.label.text()
        self.label.setText(text + "-")

    def method_multiply(self):
        text = self.label.text()
        self.label.setText(text + "*")

    def method_divide(self):
        text = self.label.text()
        self.label.setText(text + "/")

    def method_clear(self):
        self.label.setText("")

    def method_equals(self):
        text=self.label.text()

        try:
            ans=eval(text)
            self.label.setText(str(ans))
        except:
            self.label.setText("Wrong Input")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calc!"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.multiply.setText(_translate("MainWindow", "X"))
        self.divide.setText(_translate("MainWindow", "÷"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.equals.setText(_translate("MainWindow", "="))
        self.clear.setText(_translate("MainWindow", "AC"))
        self.label_2.setText(_translate("MainWindow", "Made with  ❤"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
